#!/usr/bin/env pwsh
# sync-memory-in.ps1 — SessionStart hook pour le pattern .claude/memory/
# Generated by /init-repo. Edit if needed.
#
# Rôle :
#   1. Faire un git pull silencieux si le repo a un remote (pour récupérer modifs mémoire d'autres machines)
#   2. Reporter l'état de .claude/memory/ à Claude (count + canary check)
#   3. Détecter si MEMORY.md a >30 entries (alerte hygiène)

$ErrorActionPreference = "SilentlyContinue"
$repoRoot = $env:CLAUDE_PROJECT_DIR
if (-not $repoRoot) { $repoRoot = (Get-Location).Path }

$memoryDir = Join-Path $repoRoot ".claude/memory"

# Si pas de mémoire versionnée → silencieux, fin
if (-not (Test-Path $memoryDir)) { exit 0 }

# Pull silencieux si remote configuré (et qu'on est sur la branche par défaut)
$gitDir = Join-Path $repoRoot ".git"
if (Test-Path $gitDir) {
    try {
        $remote = git -C $repoRoot remote 2>$null | Select-Object -First 1
        if ($remote) {
            $branch = git -C $repoRoot rev-parse --abbrev-ref HEAD 2>$null
            git -C $repoRoot fetch --quiet $remote $branch 2>$null
            # Pull seulement si la copie locale n'a PAS de modifs dans .claude/memory/
            $dirty = git -C $repoRoot status --short -- .claude/memory/ 2>$null
            if (-not $dirty) {
                git -C $repoRoot pull --ff-only --quiet $remote $branch 2>$null
            }
        }
    } catch {}
}

# Status mémoire
$memoryFiles = Get-ChildItem -Path $memoryDir -Filter "*.md" -File 2>$null
$count = $memoryFiles.Count
$memoryIndex = Join-Path $memoryDir "MEMORY.md"

Write-Host "🧠 Memory: $count files in .claude/memory/" -ForegroundColor Cyan

# Canary: alerte si MEMORY.md inexistant
if (-not (Test-Path $memoryIndex)) {
    Write-Host "  ⚠ MEMORY.md absent — l'index est manquant, contexte démarrage dégradé" -ForegroundColor Yellow
    exit 0
}

# Canary: count lignes index (proxy pour "trop d'entries")
$indexLines = (Get-Content $memoryIndex | Where-Object { $_ -match "^\s*-\s*\[" }).Count
if ($indexLines -gt 30) {
    Write-Host "  ⚠ MEMORY.md a $indexLines entries (cible <30) — propose /bye + élagage à la fin de session" -ForegroundColor Yellow
}

# Canary: fichier .canary vide attendu
$canary = Join-Path $memoryDir ".canary"
if ((Test-Path $canary) -and ((Get-Item $canary).Length -gt 0)) {
    Write-Host "  ⚠ .canary non vide — possible corruption mémoire" -ForegroundColor Red
}

exit 0
