#!/usr/bin/env pwsh
# sync-memory-out.ps1 — Stop hook pour le pattern .claude/memory/
# Generated by /init-repo. Edit if needed.
#
# Rôle :
#   1. Détecter si la session a modifié .claude/memory/
#   2. Alerter Robin pour qu'il fasse /bye (validation + commit)

$ErrorActionPreference = "SilentlyContinue"
$repoRoot = $env:CLAUDE_PROJECT_DIR
if (-not $repoRoot) { $repoRoot = (Get-Location).Path }

$memoryDir = Join-Path $repoRoot ".claude/memory"
if (-not (Test-Path $memoryDir)) { exit 0 }

$gitDir = Join-Path $repoRoot ".git"
if (-not (Test-Path $gitDir)) { exit 0 }

# Modifs mémoire non commitées ?
$dirty = git -C $repoRoot status --short -- .claude/memory/ 2>$null
if ($dirty) {
    $changeCount = ($dirty | Measure-Object -Line).Lines
    Write-Host "" -ForegroundColor Yellow
    Write-Host "📝 Memory modified during session ($changeCount file(s)) — propose /bye pour valider + commit" -ForegroundColor Yellow
}

exit 0
